name: Build and Deploy VSIX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2    

    - name: Install NuGet
      run: nuget restore

    - name: Build solution
      run: msbuild /t:Restore,Build /p:Configuration=Release

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: vsix
        path: |
          **/*.vsix